### ISSUE TITLE
Ошибка:

### ISSUE THREAD

**Issue by OrioTop4ik** [dest4590/MIOXY#2]
![Снимок экрана](https://github.com/user-attachments/assets/a1a90efc-7ba8-413c-a3fc-62defb02331e)
Что делать?

**Comment by dest4590** [comment]
убрать порт

**Comment by OrioTop4ik** [comment]
![image](https://github.com/user-attachments/assets/66472055-3d27-4a41-909d-7587d7a94af4)

**Comment by dest4590** [comment]
не знаю, потом пофикшу

**Comment by OrioTop4ik** [comment]
да ну блять ну какой потом я играть хочу ааа блуууд пжжпжпж 😥😥😥😂😂😂😂😂👺👺👺👺😭😭😭😭😭
